GymHub/GymHub/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),




    #path('', views.home),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GymHub/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include


from . import views
urlpatterns=[
	path('',views.home,name='home'),
    path('pagedetail/<int:id>',views.page_detail,name='pagedetail'),
    path('faq',views.faq_list,name='faq'),
    path('enquiry',views.enquiry,name='enquiry'),
    path('gallery',views.gallery,name='gallery'),
    path('gallerydetail/<int:id>',views.gallery_detail,name='gallery_detail'),
    path('pricing',views.pricing,name='pricing'),
    path('accounts/signup',views.signup,name='signup'),
    path('checkout/<int:plan_id>',views.checkout,name='checkout'),
    path('checkout_session/<int:plan_id>',views.checkout_session,name='checkout_session'),
    path('pay_success',views.pay_success,name='pay_success'),
    path('pay_cancel',views.pay_cancel,name='pay_cancel'),
    # User Dashboard Section Start
    path('user-dashboard',views.user_dashboard,name='user_dashboard'),  
    path('update-profile',views.update_profile,name='update_profile'),
    # Trainer Login
	path('trainerlogin',views.trainerlogin,name='trainerlogin'),
    path('trainerlogout',views.trainerlogout,name='trainerlogout'),
    # Notifications
	path('notifs',views.notifs,name='notifs'),
    path('get_notifs',views.get_notifs,name='get_notifs'),
    path('mark_read_notif',views.mark_read_notif,name='mark_read_notif'),











    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GymHub/main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Banner(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length=150)

    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))

    
#pages
class Page(models.Model):
      title=models.CharField(max_length=200)
      detail=models.TextField()

      def __str__(self):
            return self.title

class Faq(models.Model):
      quest=models.TextField()
      ans=models.TextField()

      def __str__(self):
            return self.quest
      # Enquiry Model
class Enquiry(models.Model):
	full_name=models.CharField(max_length=150)
	email=models.CharField(max_length=150)
	detail=models.TextField()
	send_time=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.full_name
      

# Gallery Model
class Gallery(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="gallery/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))
	# Gallery Images
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.img.url))
	# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	validity_days=models.IntegerField(null=True)

	highlight_status=models.BooleanField(default=False, null=True) 

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	##subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title
	
	# Package Discounts
class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)
	

# Subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

@receiver(post_save,sender=User)
def create_subscriber(sender,instance,created,**kwrags):
	if created:
		Subscriber.objects.create(user=instance)

	 

    # Subscription
class Subscription(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	price=models.CharField(max_length=50)
	reg_date=models.DateField(auto_now_add=True,null=True)

class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/")
	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe('<img src="%s" width="80" />' % (self.img.url))
		else:
			return 'no-image'

	
# Notifications Json Response Via Ajax
class Notify(models.Model):
	notify_detail=models.TextField()
	read_by_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return str(self.notify_detail)
	
# Markas Read Notification By User
class NotifUserStatus(models.Model):
	notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Notification Status'


	
# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.user)

GymHub/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
	class Meta:
		model=models.Enquiry
		fields=('full_name','email','detail')

class Signup(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')


class TrainerLoginForm(forms.ModelForm):
	class Meta:
		model=models.Trainer
		fields=('username','pwd')

GymHub/main/views.py
from django.shortcuts import render
from . import models
from . import forms
from django.db.models import Count
import stripe
from django.shortcuts import redirect
from django.template.loader import get_template
from django.core import serializers
from django.http import JsonResponse
from datetime import timedelta




#homepage
def home(request):
    banner = models.Banner.objects.all()
    services = models.Service.objects.all()[:3]
    gimgs = models.GalleryImage.objects.all().order_by('-id')[:9]

    return render(request, 'home.html', {'banner': banner, 'services': services, 'gimgs': gimgs})


# PageDetail
def page_detail(request,id):
	page=models.Page.objects.get(id=id)
	return render(request, 'page.html',{'page':page})
#FAQ
def faq_list(request):
	faq=models.Faq.objects.all()
	return render(request, 'faq.html',{'faq':faq})

# Enquiry
def enquiry(request):
	msg=''
	if request.method=='POST':
		form=forms.EnquiryForm(request.POST)
		if form.is_valid():
			form.save()
			msg='Data has been saved'
	form=forms.EnquiryForm
	return render(request, 'enquiry.html',{'form':form,'msg':msg})

# Show galleries
def gallery(request):
	gallery=models.Gallery.objects.all().order_by('-id')
	return render(request, 'gallery.html',{'gallerys':gallery})

# Show gallery photos
def gallery_detail(request,id):
	gallery=models.Gallery.objects.get(id=id)
	gallery_imgs=models.GalleryImage.objects.filter(gallery=gallery).order_by('-id')
	return render(request, 'gallery_imgs.html',{'gallery_imgs':gallery_imgs,'gallery':gallery})


# Subscription Plans
def pricing(request):
	pricing=models.SubPlan.objects.annotate(total_members=Count('subscription__id')).all().order_by('price')
	dfeatures=models.SubPlanFeature.objects.all();
	return render(request, 'pricing.html',{'plans':pricing,'dfeatures':dfeatures})
	
# SignUp
def signup(request):
    msg = None
    if request.method == 'POST':
        form = forms.Signup(request.POST)
        if form.is_valid():
            form.save()
            msg = 'Thank you for registering.'
    else:
        form = forms.Signup()
    return render(request, 'registration/signup.html', {'form': form, 'msg': msg})

# Checkout
def checkout(request,plan_id):
	planDetail=models.SubPlan.objects.get(pk=plan_id)
	return render(request, 'checkout.html',{'plan':planDetail})

stripe.api_key='sk_test_51OpBhNSB2N5bDLgLhf25MrdktEHKdXRI4n4prI0YajboUFWUSkO2Di262WWQX3jf8LiNY8bdQNODc5du3yfpjsuz00zIpiAVB8'
def checkout_session(request, plan_id):
    plan = models.SubPlan.objects.get(pk=plan_id)

    # Assuming each SubPlan has a corresponding PlanDiscount
    # plan_discount = models.PlanDiscount.objects.get(subplan=plan)

    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                'currency': 'npr',
                'product_data': {
                    'name': plan.title,
                },
                'unit_amount': (plan.price) * 100,
            },
            'quantity': 1,
        }],
        mode='payment',
        success_url='http://127.0.0.1:8000/pay_success?session_id={CHECKOUT_SESSION_ID}',
        cancel_url='http://127.0.0.1:8000/pay_cancel',
        client_reference_id=plan_id
    )

    return redirect(session.url, code=303)

# Success
from django.core.mail import EmailMessage

def pay_success(request):
	session = stripe.checkout.Session.retrieve(request.GET['session_id'])
	plan_id=session.client_reference_id
	plan=models.SubPlan.objects.get(pk=plan_id)
	user=request.user
	models.Subscription.objects.create(
		plan=plan,
		user=user,
		price=plan.price
	)
	subject='Order Email'
	html_content=get_template('orderemail.html').render({'title':plan.title})
	from_email='tom65803@gmail.com'

	msg = EmailMessage(subject, html_content, from_email, ['tate@gmail.com'])
	msg.content_subtype = "html"  # Main content is now text/html
	msg.send()

	return render(request, 'success.html')

def pay_cancel(request):
	return render(request, 'cancel.html')


# User Dashboard Section Start
# User Dashboard Section Start
def user_dashboard(request):
	current_plan=models.Subscription.objects.get(user=request.user)
	my_trainer=models.AssignSubscriber.objects.get(user=request.user)
	enddate=current_plan.reg_date+timedelta(days=current_plan.plan.validity_days)




	data=models.Notify.objects.all().order_by('-id')
	notifStatus=False
	jsonData=[]
	totalUnread=0
	for d in data:
		try:
			notifStatusData=models.NotifUserStatus.objects.get(user=request.user,notif=d)
			if notifStatusData:
				notifStatus=True
		except models.NotifUserStatus.DoesNotExist:
			notifStatus=False
		if not notifStatus:
			totalUnread=totalUnread+1
		
	return render(request, 'user/dashboard.html',{'current_plan':current_plan, 'my_trainer':my_trainer,'total_unread':'totalUnread','enddate':enddate

	})
# Edit Form
# Edit Form
def update_profile(request):
	msg=None
	if request.method=='POST':
		form=forms.ProfileForm(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			msg='Data has been saved'
	form=forms.ProfileForm(instance=request.user)
	return render(request, 'user/update-profile.html',{'form':form,'msg':msg})


# trainer login
def trainerlogin(request):
	msg=''
	if request.method=='POST':
		username=request.POST['username']
		pwd=request.POST['pwd']
		trainer=models.Trainer.objects.filter(username=username,pwd=pwd).count()
		if trainer > 0:
			request.session['trainerLogin']=True
			return redirect('/trainer_dashboard')



			
			
		else:
			msg='Invalid!!'
	form=forms.TrainerLoginForm
	return render(request, 'trainer/login.html',{'form':form,'msg':msg})

# Trainer Logout
def trainerlogout(request):
	del request.session['trainerLogin']
	return redirect('/trainerlogin')


# Notifications
def notifs(request):
	data=models.Notify.objects.all().order_by('-id')
	return render(request, 'notifs.html',{'data':data})
	

# Get All Notifications
def get_notifs(request):
	data=models.Notify.objects.all().order_by('-id')
	notifStatus=False
	jsonData=[]
	totalUnread=0
	for d in data:
		try:
			notifStatusData=models.NotifUserStatus.objects.get(user=request.user,notif=d)
			if notifStatusData:
				notifStatus=True
		except models.NotifUserStatus.DoesNotExist:
			notifStatus=False
		if not notifStatus:
			totalUnread=totalUnread+1
		jsonData.append({
				'pk':d.id,
				'notify_detail':d.notify_detail,
				'notifStatus':notifStatus
			})
	return JsonResponse({'data':jsonData,'totalUnread':totalUnread})
# Markas Read Notification By User
# Mark Read By user
def mark_read_notif(request):
	notif=request.GET['notif']
	notif=models.Notify.objects.get(pk=notif)
	user=request.user
	models.NotifUserStatus.objects.create(notif=notif,user=user,status=True)
	return JsonResponse({'bool':True})

GymHub/main/templates/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" type="text/css" href="node_modules/bootstrap-icons/font/bootstrap-icons.css" />
    <!-- jquery -->
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <title>Home - Arnold GYM</title>
</head>
<body>
<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Arnold GYM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-sm btn-dark text-white" href="{% url 'enquiry' %}">Enquiry</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        My Account
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        {% if not request.user.is_authenticated %}
                        {% if request.session.trainerLogin %}
                        <li><a class="dropdown-item" href="{% url 'trainerlogout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a></li>

                        <li><a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Logout</button>
                            </form>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Header End -->
<!-- Header End -->

{% block content %}

{% endblock %}

<!-- Footer Start -->
<footer class="container py-5">
    <p class="float-end"><a href="#">Back to top</a></p>
    <a href="{% url 'pagedetail' 2 %}">Privacy</a> ·
    <a href="{% url 'pagedetail' 3 %}">Terms</a> .
    <a href="{% url 'faq' %}">FAQ</a>
    <a href="#">Contact Us</a>
</footer>
<!-- Bootstrap Bundle -->
</body>
</html>

GymHub/main/templates/cancel.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3>Sorry!! Please try again</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

GymHub/main/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>Plan Detail</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{plan.title}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>${{plan.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>30</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>15</td>
									</tr>
									<tr>
										<th>Balance Seats</th>
										<td>15</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
                                    {% for feature in plan.subplanfeature_set.all %}
                                    <li>{{feature.title}}</li>
                                    {% endfor %}
					            </ul>
							</td>
							<td>
								<table class="table table-bordered">
                                    {% for discount in plan.plandiscount_set.all %}
							            <tr>
											<td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
											<th><label for="validity{{discount.id}}">{{discount.total_months}} Month</label></th>
											<td>{{discount.total_discount}}%</td>
										</tr>
					            	{% endfor %}
								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b><span class="totalAmount">150</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
                                <form method="post" action="{% url 'checkout_session' plan.id %}">
									{% csrf_token %}
									<input type="submit" value="Proceed to Payment" class="btn btn-primary" />
								</form>
							</td>
						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>
</main>
<script type="text/javascript">
    $(document).ready(function(){
        $(".select-validity").on('click',function(){
            var _planPrice=$(this).attr('data-planprice');
            var _planValid=$(this).val();
            var _planDisc=$(this).attr('data-discount');
            var _totalPrice=_planPrice*_planValid;
            var _calDisc = 0;

            if(_planDisc>0){
                _calDisc=_totalPrice*_planDisc/100;
                _calDisc=_totalPrice-_calDisc;
            }else{
                _calDisc=_planPrice;
            }

            // Display both original price and discounted price
            var _displayText = "$" + _calDisc.toFixed(2);
            if (_totalPrice != _calDisc) {
                _displayText += " (Before Discount: $" + _totalPrice.toFixed(2) + ")";
            }

            $(".totalAmount").text(_displayText);
        });
    });
</script>



    {% endblock %}

GymHub/main/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/1.jpg' %}" class="img-fluid" /> 
				</div>
				<div class="col-md-6">
					{% if msg %}
					<p class="text-success">{{msg}}</p>
					{% endif %}
					<form method="post" action="{% url 'enquiry' %}">
						{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

GymHub/main/templates/faq.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
				{% for faq in faq %}
				  <div class="accordion-item">
				    <h2 class="accordion-header" id="headingOne">
				      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
				        {{faq.quest}}
				      </button>
				    </h2>
				    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				      <div class="accordion-body">
				        {{faq.ans}}
				      </div>
				    </div>
				  </div>
				  {% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

GymHub/main/templates/gallery.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
			<div class="row">
				{% for gallery in gallerys %}
				<div class="col-md-4 mb-4">
					<div class="card">
					  <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title}}">
					  <div class="card-body">
					    <h5 class="card-title">{{gallery.title}}</h5>
					    <p class="card-text">{{gallery.detail}}</p>
					    <a href="{% url 'gallery_detail' gallery.id %}" class="btn btn-primary">View All</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

GymHub/main/templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load mathfilters %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
<section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
<main>
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
  
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
        <div class="card-header py-3 text-white bg-primary border-primary">
          {% else %}
        <div class="card-header py-3">
          {% endif %}
          <h4 class="my-0 fw-normal">{{plan.title}}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">${{plan.price}}
            <small class="text-muted fw-light">/{{plan.validity_days}}</small>
          </h1>
          <p class="text-success">Member Capacity {{plan.max_member|sub:plan.total_members}}</p>
          <ul class="list-unstyled mt-3 mb-4">
            {% for feature in plan.subplanfeature_set.all %}
            <li>{{feature.title}}</li>
            {% endfor %}
          </ul> 
          {% if request.user.is_authenticated %} 
          <a href ="{% url 'checkout' plan.id %}"class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% else %}
          <a href ="{% url 'login' %}"  class="w-100 btn btn-lg btn-outline-primary">Get started</a>


          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <h2 class="display-6 text-center mb-4">Compare plans</h2>
  <div class="table-responsive">
    <table class="table text-center">
      <thead>
        <tr>
          <th style="width: 34%;"></th>
          {% for plan in plans %}
          <th style="width: 22%;">{{plan.title}}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for feature in dfeatures %}
        <tr>
          <th scope="row" class="text-start">{{feature.title}}</th>
          {% for plan in plans %}
          <td>
            {% if plan in feature.subplan.all %}
            <i class="bi bi-check-lg"></i>
            {% else %}
            <i class="bi bi-x-lg text-danger"></i>
            {% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
</section>
{% endblock %}